# Generated by Django 5.2.7 on 2025-10-25 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craigslist_id', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
