# Generated by Django 5.2.7 on 2025-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='data_quality',
            field=models.IntegerField(default=0),
        ),
    ]
