# Generated by Django 5.2.7 on 2025-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_data_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cats_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='dogs_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry_type',
            field=models.CharField(blank=True, choices=[('none', 'No Laundry'), ('in_unit', 'In-Unit'), ('on_site', 'On-Site/In Building')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, choices=[('none', 'No Parking'), ('street', 'Street Parking'), ('off_street', 'Off-Street Parking'), ('garage', 'Garage'), ('carport', 'Carport')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
