# Generated by Django 5.2.7 on 2025-11-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_address_listing_bathrooms_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cats_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='dogs_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
