# Generated by Django 5.2.7 on 2026-02-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='below_market',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='best_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_sqft',
            field=models.IntegerField(default=0),
        ),
    ]
