export const mockListings = [
  {
    id: 1,
    craigslist_id: "7789234501",
    url: "https://sfbay.craigslist.org/sfc/apa/d/spacious-2br-mission/7789234501.html",
    title: "Spacious 2BR in Mission District - Hardwood Floors",
    price: 3200,
    location: "mission district",
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 950,
    address: "123 Valencia St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "street",
    extra_amenities: ["hardwood floors", "dishwasher", "balcony"],
    latitude: 37.7599,
    longitude: -122.4148,
    scraped_at: "2025-01-13T10:30:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 2,
    craigslist_id: "7789234502",
    url: "https://sfbay.craigslist.org/sfc/apa/d/cozy-studio-noe-valley/7789234502.html",
    title: "Cozy Studio in Noe Valley - Pet Friendly",
    price: 2400,
    location: "noe valley",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 500,
    address: "456 24th St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "shared",
    parking: "garage",
    extra_amenities: ["updated kitchen", "garden access"],
    latitude: 37.751,
    longitude: -122.4315,
    scraped_at: "2025-01-13T09:15:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 3,
    craigslist_id: "7789234503",
    url: "https://sfbay.craigslist.org/sfc/apa/d/modern-1br-soma/7789234503.html",
    title: "Modern 1BR in SOMA - Luxury Building",
    price: 2850,
    location: "soma / south beach",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    address: "789 Folsom St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "included",
    extra_amenities: ["gym access", "rooftop deck", "concierge"],
    latitude: 37.7796,
    longitude: -122.3979,
    scraped_at: "2025-01-13T08:45:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 4,
    craigslist_id: "7789234504",
    url: "https://sfbay.craigslist.org/sfc/apa/d/charming-3br-castro/7789234504.html",
    title: "Charming 3BR in Castro - Victorian Style",
    price: 4200,
    location: "castro / upper market",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    address: "321 Castro St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["fireplace", "bay windows", "original details"],
    latitude: 37.7609,
    longitude: -122.435,
    scraped_at: "2025-01-13T07:20:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 5,
    craigslist_id: "7789234505",
    url: "https://sfbay.craigslist.org/sfc/apa/d/bright-1br-haight-ashbury/7789234505.html",
    title: "Bright 1BR in Haight-Ashbury - Great Location",
    price: 2650,
    location: "haight ashbury",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    address: "555 Haight St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "shared",
    parking: "street",
    extra_amenities: ["high ceilings", "natural light"],
    latitude: 37.7718,
    longitude: -122.4467,
    scraped_at: "2025-01-13T06:50:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 6,
    craigslist_id: "7789234506",
    url: "https://sfbay.craigslist.org/sfc/apa/d/updated-2br-russian-hill/7789234506.html",
    title: "Updated 2BR in Russian Hill - City Views",
    price: 3800,
    location: "russian hill",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    address: "678 Lombard St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "included",
    extra_amenities: ["city views", "stainless appliances", "marble counters"],
    latitude: 37.8019,
    longitude: -122.4187,
    scraped_at: "2025-01-13T06:15:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 7,
    craigslist_id: "7789234507",
    url: "https://sfbay.craigslist.org/sfc/apa/d/affordable-studio-tenderloin/7789234507.html",
    title: "Affordable Studio in Tenderloin - Good Deal",
    price: 1850,
    location: "tenderloin",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    address: "234 Turk St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "coin",
    parking: "none",
    extra_amenities: [],
    latitude: 37.7823,
    longitude: -122.4134,
    scraped_at: "2025-01-12T23:45:00Z",
    active: true,
    data_quality: "partial",
  },
  {
    id: 8,
    craigslist_id: "7789234508",
    url: "https://sfbay.craigslist.org/sfc/apa/d/renovated-1br-north-beach/7789234508.html",
    title: "Renovated 1BR in North Beach - Walk to Everything",
    price: 2900,
    location: "north beach / telegraph hill",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    address: "890 Columbus Ave, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-building",
    parking: "street",
    extra_amenities: ["exposed brick", "new kitchen", "walk-in closet"],
    latitude: 37.8008,
    longitude: -122.4098,
    scraped_at: "2025-01-12T22:30:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 9,
    craigslist_id: "7789234509",
    url: "https://sfbay.craigslist.org/sfc/apa/d/large-2br-sunset/7789234509.html",
    title: "Large 2BR in Sunset District - Quiet Neighborhood",
    price: 2600,
    location: "sunset / parkside",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    address: "1234 Irving St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["backyard", "storage", "near park"],
    latitude: 37.7637,
    longitude: -122.4704,
    scraped_at: "2025-01-12T21:00:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 10,
    craigslist_id: "7789234510",
    url: "https://sfbay.craigslist.org/sfc/apa/d/luxury-studio-financial-district/7789234510.html",
    title: "Luxury Studio in Financial District - High Rise",
    price: 2700,
    location: "financial district",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 550,
    address: "456 Market St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "included",
    extra_amenities: ["doorman", "gym", "pool", "city views"],
    latitude: 37.7909,
    longitude: -122.3998,
    scraped_at: "2025-01-12T20:15:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 11,
    craigslist_id: "7789234511",
    url: "https://sfbay.craigslist.org/sfc/apa/d/beautiful-2br-pacific-heights/7789234511.html",
    title: "Beautiful 2BR in Pacific Heights - Premium Location",
    price: 4500,
    location: "pacific heights",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: "789 Pacific Ave, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["bay views", "chef's kitchen", "hardwood"],
    latitude: 37.7946,
    longitude: -122.4291,
    scraped_at: "2025-01-12T19:30:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 12,
    craigslist_id: "7789234512",
    url: "https://sfbay.craigslist.org/sfc/apa/d/simple-1br-mission/7789234512.html",
    title: "Simple 1BR in Mission - Good Value",
    price: 2300,
    location: "mission district",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    address: "987 Mission St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "coin",
    parking: "street",
    extra_amenities: ["near BART", "restaurants nearby"],
    latitude: 37.7577,
    longitude: -122.4175,
    scraped_at: "2025-01-12T18:45:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 13,
    craigslist_id: "7789234513",
    url: "https://sfbay.craigslist.org/sfc/apa/d/spacious-3br-richmond/7789234513.html",
    title: "Spacious 3BR in Richmond District - Family Friendly",
    price: 3600,
    location: "richmond / seacliff",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1300,
    address: "345 Clement St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["fenced yard", "updated bathrooms", "near schools"],
    latitude: 37.7827,
    longitude: -122.4632,
    scraped_at: "2025-01-12T17:20:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 14,
    craigslist_id: "7789234514",
    url: "https://sfbay.craigslist.org/sfc/apa/d/trendy-1br-hayes-valley/7789234514.html",
    title: "Trendy 1BR in Hayes Valley - Hip Neighborhood",
    price: 2950,
    location: "hayes valley",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    address: "567 Hayes St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "street",
    extra_amenities: ["modern finishes", "walk to shops", "hardwood"],
    latitude: 37.7758,
    longitude: -122.4264,
    scraped_at: "2025-01-12T16:00:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 15,
    craigslist_id: "7789234515",
    url: "https://sfbay.craigslist.org/sfc/apa/d/cute-studio-potrero-hill/7789234515.html",
    title: "Cute Studio in Potrero Hill - Sunny Location",
    price: 2200,
    location: "potrero hill",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    address: "890 Potrero Ave, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "shared",
    parking: "street",
    extra_amenities: ["lots of light", "private entrance"],
    latitude: 37.7587,
    longitude: -122.4072,
    scraped_at: "2025-01-12T15:10:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 16,
    craigslist_id: "7789234516",
    url: "https://sfbay.craigslist.org/sfc/apa/d/elegant-2br-nob-hill/7789234516.html",
    title: "Elegant 2BR in Nob Hill - Classic Building",
    price: 3900,
    location: "nob hill",
    bedrooms: 2,
    bathrooms: 1.5,
    sqft: 1000,
    address: "123 California St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "valet",
    extra_amenities: ["doorman", "crown molding", "formal dining"],
    latitude: 37.7917,
    longitude: -122.4103,
    scraped_at: "2025-01-12T14:25:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 17,
    craigslist_id: "7789234517",
    url: "https://sfbay.craigslist.org/sfc/apa/d/basic-1br-soma/7789234517.html",
    title: "Basic 1BR in SOMA - Near Tech Companies",
    price: 2750,
    location: "soma / south beach",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    address: "234 Howard St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "coin",
    parking: "none",
    extra_amenities: ["near Caltrain", "bike storage"],
    latitude: 37.7875,
    longitude: -122.3967,
    scraped_at: "2025-01-12T13:40:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 18,
    craigslist_id: "7789234518",
    url: "https://sfbay.craigslist.org/sfc/apa/d/quiet-2br-marina/7789234518.html",
    title: "Quiet 2BR in Marina District - Near Water",
    price: 3700,
    location: "marina / cow hollow",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    address: "567 Chestnut St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["patio", "updated kitchen", "near marina green"],
    latitude: 37.8019,
    longitude: -122.4376,
    scraped_at: "2025-01-12T12:15:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 19,
    craigslist_id: "7789234519",
    url: "https://sfbay.craigslist.org/sfc/apa/d/artistic-studio-mission/7789234519.html",
    title: "Artistic Studio in Mission - Creative Space",
    price: 2100,
    location: "mission district",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 500,
    address: "678 Valencia St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "shared",
    parking: "street",
    extra_amenities: ["high ceilings", "artistic building", "murals nearby"],
    latitude: 37.7589,
    longitude: -122.4215,
    scraped_at: "2025-01-12T11:30:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 20,
    craigslist_id: "7789234520",
    url: "https://sfbay.craigslist.org/sfc/apa/d/huge-3br-excelsior/7789234520.html",
    title: "Huge 3BR in Excelsior - Best Value",
    price: 3000,
    location: "excelsior",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    address: "890 Mission St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "driveway",
    extra_amenities: ["huge space", "yard", "storage"],
    latitude: 37.7246,
    longitude: -122.4273,
    scraped_at: "2025-01-12T10:45:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 21,
    craigslist_id: "7789234521",
    url: "https://sfbay.craigslist.org/sfc/apa/d/modern-1br-dogpatch/7789234521.html",
    title: "Modern 1BR in Dogpatch - Newly Renovated",
    price: 2800,
    location: "potrero hill",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    address: "345 3rd St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: true,
    laundry_type: "in-unit",
    parking: "included",
    extra_amenities: ["new construction", "tech amenities", "rooftop"],
    latitude: 37.7676,
    longitude: -122.389,
    scraped_at: "2025-01-12T09:20:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 22,
    craigslist_id: "7789234522",
    url: "https://sfbay.craigslist.org/sfc/apa/d/vintage-2br-lower-haight/7789234522.html",
    title: "Vintage 2BR in Lower Haight - Character",
    price: 3100,
    location: "haight ashbury",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    address: "234 Haight St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "shared",
    parking: "street",
    extra_amenities: ["vintage charm", "original details", "wood burning stove"],
    latitude: 37.7725,
    longitude: -122.4289,
    scraped_at: "2025-01-12T08:35:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 23,
    craigslist_id: "7789234523",
    url: "https://sfbay.craigslist.org/sfc/apa/d/sunny-1br-inner-richmond/7789234523.html",
    title: "Sunny 1BR in Inner Richmond - Peaceful",
    price: 2450,
    location: "richmond / seacliff",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    address: "567 Balboa St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "garage",
    extra_amenities: ["quiet street", "near park", "updated"],
    latitude: 37.7763,
    longitude: -122.4687,
    scraped_at: "2025-01-12T07:50:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 24,
    craigslist_id: "7789234524",
    url: "https://sfbay.craigslist.org/sfc/apa/d/penthouse-studio-downtown/7789234524.html",
    title: "Penthouse Studio Downtown - Amazing Views",
    price: 3100,
    location: "financial district",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 600,
    address: "890 Market St, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "valet",
    extra_amenities: ["360 views", "floor to ceiling windows", "luxury building"],
    latitude: 37.7842,
    longitude: -122.4066,
    scraped_at: "2025-01-12T06:30:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 25,
    craigslist_id: "7789234525",
    url: "https://sfbay.craigslist.org/sfc/apa/d/affordable-2br-bayview/7789234525.html",
    title: "Affordable 2BR in Bayview - Great Deal",
    price: 2400,
    location: "bayview",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    address: "123 3rd St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "coin",
    parking: "street",
    extra_amenities: ["spacious rooms", "near transit"],
    latitude: 37.7299,
    longitude: -122.3893,
    scraped_at: "2025-01-12T05:15:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 26,
    craigslist_id: "7789234526",
    url: "https://sfbay.craigslist.org/sfc/apa/d/loft-1br-soma/7789234526.html",
    title: "Loft-Style 1BR in SOMA - Industrial Chic",
    price: 3000,
    location: "soma / south beach",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    address: "456 Townsend St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "included",
    extra_amenities: ["exposed brick", "high ceilings", "open floor plan"],
    latitude: 37.776,
    longitude: -122.3956,
    scraped_at: "2025-01-11T23:45:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 27,
    craigslist_id: "7789234527",
    url: "https://sfbay.craigslist.org/sfc/apa/d/garden-level-studio-noe/7789234527.html",
    title: "Garden Level Studio in Noe Valley - Private Entry",
    price: 2250,
    location: "noe valley",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    address: "789 Church St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: true,
    laundry_type: "shared",
    parking: "street",
    extra_amenities: ["private garden", "separate entrance", "quiet"],
    latitude: 37.7498,
    longitude: -122.4282,
    scraped_at: "2025-01-11T22:20:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 28,
    craigslist_id: "7789234528",
    url: "https://sfbay.craigslist.org/sfc/apa/d/premium-2br-twin-peaks/7789234528.html",
    title: "Premium 2BR in Twin Peaks - Stunning Views",
    price: 4000,
    location: "twin peaks",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    address: "321 Twin Peaks Blvd, San Francisco, CA",
    cats_allowed: false,
    dogs_allowed: false,
    laundry_type: "in-unit",
    parking: "garage",
    extra_amenities: ["panoramic views", "modern kitchen", "deck"],
    latitude: 37.7544,
    longitude: -122.4477,
    scraped_at: "2025-01-11T21:00:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 29,
    craigslist_id: "7789234529",
    url: "https://sfbay.craigslist.org/sfc/apa/d/walkup-1br-north-beach/7789234529.html",
    title: "Walk-up 1BR in North Beach - European Feel",
    price: 2600,
    location: "north beach / telegraph hill",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    address: "654 Grant Ave, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "shared",
    parking: "none",
    extra_amenities: ["neighborhood charm", "near cafes", "walk to everything"],
    latitude: 37.7982,
    longitude: -122.4076,
    scraped_at: "2025-01-11T20:10:00Z",
    active: true,
    data_quality: "complete",
  },
  {
    id: 30,
    craigslist_id: "7789234530",
    url: "https://sfbay.craigslist.org/sfc/apa/d/updated-1br-outer-sunset/7789234530.html",
    title: "Updated 1BR in Outer Sunset - Near Ocean",
    price: 2500,
    location: "sunset / parkside",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    address: "234 Judah St, San Francisco, CA",
    cats_allowed: true,
    dogs_allowed: false,
    laundry_type: "in-building",
    parking: "street",
    extra_amenities: ["near ocean beach", "quiet", "updated appliances"],
    latitude: 37.7622,
    longitude: -122.4975,
    scraped_at: "2025-01-11T19:00:00Z",
    active: true,
    data_quality: "complete",
  },
];

export const mockAnalytics = {
  overall: {
    total_listings: 30,
    avg_price: 2941.67,
    median_price: 2850,
    min_price: 1850,
    max_price: 4500,
    avg_sqft: 742,
    median_sqft: 700,
    avg_price_per_sqft: 4.12,
    total_bedrooms_available: {
      0: 9,
      1: 12,
      2: 7,
      3: 2,
    },
  },
  neighborhoods: [
    {
      location: "mission district",
      count: 4,
      avg_price: 2650,
      median_price: 2500,
      min_price: 2100,
      max_price: 3200,
      avg_sqft: 750,
      price_change_30d: 2.5,
    },
    {
      location: "soma / south beach",
      count: 4,
      avg_price: 2850,
      median_price: 2825,
      min_price: 2750,
      max_price: 3000,
      avg_sqft: 712,
      price_change_30d: 3.8,
    },
    {
      location: "noe valley",
      count: 3,
      avg_price: 2350,
      median_price: 2400,
      min_price: 2250,
      max_price: 2400,
      avg_sqft: 467,
      price_change_30d: 1.2,
    },
    {
      location: "castro / upper market",
      count: 1,
      avg_price: 4200,
      median_price: 4200,
      min_price: 4200,
      max_price: 4200,
      avg_sqft: 1200,
      price_change_30d: -1.5,
    },
    {
      location: "haight ashbury",
      count: 2,
      avg_price: 2875,
      median_price: 2875,
      min_price: 2650,
      max_price: 3100,
      avg_sqft: 750,
      price_change_30d: 0.8,
    },
    {
      location: "russian hill",
      count: 1,
      avg_price: 3800,
      median_price: 3800,
      min_price: 3800,
      max_price: 3800,
      avg_sqft: 1000,
      price_change_30d: 2.1,
    },
    {
      location: "north beach / telegraph hill",
      count: 2,
      avg_price: 2750,
      median_price: 2750,
      min_price: 2600,
      max_price: 2900,
      avg_sqft: 675,
      price_change_30d: 1.9,
    },
    {
      location: "richmond / seacliff",
      count: 2,
      avg_price: 3025,
      median_price: 3025,
      min_price: 2450,
      max_price: 3600,
      avg_sqft: 975,
      price_change_30d: -0.5,
    },
    {
      location: "potrero hill",
      count: 2,
      avg_price: 2500,
      median_price: 2500,
      min_price: 2200,
      max_price: 2800,
      avg_sqft: 575,
      price_change_30d: 4.2,
    },
    {
      location: "financial district",
      count: 2,
      avg_price: 2900,
      median_price: 2900,
      min_price: 2700,
      max_price: 3100,
      avg_sqft: 575,
      price_change_30d: 5.1,
    },
    {
      location: "pacific heights",
      count: 1,
      avg_price: 4500,
      median_price: 4500,
      min_price: 4500,
      max_price: 4500,
      avg_sqft: 1100,
      price_change_30d: 1.0,
    },
    {
      location: "marina / cow hollow",
      count: 1,
      avg_price: 3700,
      median_price: 3700,
      min_price: 3700,
      max_price: 3700,
      avg_sqft: 950,
      price_change_30d: 2.3,
    },
    {
      location: "tenderloin",
      count: 1,
      avg_price: 1850,
      median_price: 1850,
      min_price: 1850,
      max_price: 1850,
      avg_sqft: 400,
      price_change_30d: -2.1,
    },
    {
      location: "sunset / parkside",
      count: 1,
      avg_price: 2600,
      median_price: 2600,
      min_price: 2600,
      max_price: 2600,
      avg_sqft: 900,
      price_change_30d: 0.3,
    },
    {
      location: "hayes valley",
      count: 1,
      avg_price: 2950,
      median_price: 2950,
      min_price: 2950,
      max_price: 2950,
      avg_sqft: 700,
      price_change_30d: 3.5,
    },
    {
      location: "nob hill",
      count: 1,
      avg_price: 3900,
      median_price: 3900,
      min_price: 3900,
      max_price: 3900,
      avg_sqft: 1000,
      price_change_30d: 1.8,
    },
  ],
  price_distribution: [
    {
      range: "Under $2000",
      count: 1,
      percentage: 3.3,
    },
    {
      range: "$2000-$2500",
      count: 7,
      percentage: 23.3,
    },
    {
      range: "$2500-$3000",
      count: 12,
      percentage: 40.0,
    },
    {
      range: "$3000-$3500",
      count: 5,
      percentage: 16.7,
    },
    {
      range: "$3500-$4000",
      count: 3,
      percentage: 10.0,
    },
    {
      range: "Over $4000",
      count: 2,
      percentage: 6.7,
    },
  ],
  good_deals: [
    {
      id: 2,
      craigslist_id: "7789234502",
      title: "Cozy Studio in Noe Valley - Pet Friendly",
      price: 2400,
      location: "noe valley",
      bedrooms: 0,
      sqft: 500,
      price_per_sqft: 4.8,
      neighborhood_avg: 2350,
      savings: 0,
      percentage_below_avg: 0,
      deal_score: 8.2,
      reason: "Great amenities and pet-friendly in desirable neighborhood",
    },
    {
      id: 7,
      craigslist_id: "7789234507",
      title: "Affordable Studio in Tenderloin - Good Deal",
      price: 1850,
      location: "tenderloin",
      bedrooms: 0,
      sqft: 400,
      price_per_sqft: 4.63,
      neighborhood_avg: 1850,
      savings: 0,
      percentage_below_avg: 0,
      deal_score: 7.5,
      reason: "Most affordable option in dataset",
    },
    {
      id: 9,
      craigslist_id: "7789234509",
      title: "Large 2BR in Sunset District - Quiet Neighborhood",
      price: 2600,
      location: "sunset / parkside",
      bedrooms: 2,
      sqft: 900,
      price_per_sqft: 2.89,
      neighborhood_avg: 2600,
      savings: 0,
      percentage_below_avg: 0,
      deal_score: 9.1,
      reason: "Excellent price per sqft with in-unit laundry and parking",
    },
    {
      id: 12,
      craigslist_id: "7789234512",
      title: "Simple 1BR in Mission - Good Value",
      price: 2300,
      location: "mission district",
      bedrooms: 1,
      sqft: 600,
      price_per_sqft: 3.83,
      neighborhood_avg: 2650,
      savings: 350,
      percentage_below_avg: 13.2,
      deal_score: 8.7,
      reason: "13% below neighborhood average with pet-friendly policy",
    },
    {
      id: 15,
      craigslist_id: "7789234515",
      title: "Cute Studio in Potrero Hill - Sunny Location",
      price: 2200,
      location: "potrero hill",
      bedrooms: 0,
      sqft: 450,
      price_per_sqft: 4.89,
      neighborhood_avg: 2500,
      savings: 300,
      percentage_below_avg: 12.0,
      deal_score: 8.4,
      reason: "12% below neighborhood average in up-and-coming area",
    },
    {
      id: 19,
      craigslist_id: "7789234519",
      title: "Artistic Studio in Mission - Creative Space",
      price: 2100,
      location: "mission district",
      bedrooms: 0,
      sqft: 500,
      price_per_sqft: 4.2,
      neighborhood_avg: 2650,
      savings: 550,
      percentage_below_avg: 20.8,
      deal_score: 9.3,
      reason: "21% below neighborhood average with unique character",
    },
    {
      id: 20,
      craigslist_id: "7789234520",
      title: "Huge 3BR in Excelsior - Best Value",
      price: 3000,
      location: "excelsior",
      bedrooms: 3,
      sqft: 1400,
      price_per_sqft: 2.14,
      neighborhood_avg: 3000,
      savings: 0,
      percentage_below_avg: 0,
      deal_score: 9.6,
      reason: "Best price per sqft in dataset with huge space and yard",
    },
    {
      id: 25,
      craigslist_id: "7789234525",
      title: "Affordable 2BR in Bayview - Great Deal",
      price: 2400,
      location: "bayview",
      bedrooms: 2,
      sqft: 800,
      price_per_sqft: 3.0,
      neighborhood_avg: 2400,
      savings: 0,
      percentage_below_avg: 0,
      deal_score: 8.9,
      reason: "Excellent value for 2BR with spacious rooms",
    },
  ],
  best_price_per_sqft: [
    {
      id: 20,
      craigslist_id: "7789234520",
      title: "Huge 3BR in Excelsior - Best Value",
      price: 3000,
      location: "excelsior",
      bedrooms: 3,
      sqft: 1400,
      price_per_sqft: 2.14,
    },
    {
      id: 9,
      craigslist_id: "7789234509",
      title: "Large 2BR in Sunset District - Quiet Neighborhood",
      price: 2600,
      location: "sunset / parkside",
      bedrooms: 2,
      sqft: 900,
      price_per_sqft: 2.89,
    },
    {
      id: 25,
      craigslist_id: "7789234525",
      title: "Affordable 2BR in Bayview - Great Deal",
      price: 2400,
      location: "bayview",
      bedrooms: 2,
      sqft: 800,
      price_per_sqft: 3.0,
    },
    {
      id: 4,
      craigslist_id: "7789234504",
      title: "Charming 3BR in Castro - Victorian Style",
      price: 4200,
      location: "castro / upper market",
      bedrooms: 3,
      sqft: 1200,
      price_per_sqft: 3.5,
    },
    {
      id: 12,
      craigslist_id: "7789234512",
      title: "Simple 1BR in Mission - Good Value",
      price: 2300,
      location: "mission district",
      bedrooms: 1,
      sqft: 600,
      price_per_sqft: 3.83,
    },
  ],
  overall_best_value: [
    {
      id: 20,
      craigslist_id: "7789234520",
      title: "Huge 3BR in Excelsior - Best Value",
      price: 3000,
      location: "excelsior",
      bedrooms: 3,
      sqft: 1400,
      price_per_sqft: 2.14,
      value_score: 9.6,
      reasons: ["Best price per sqft in dataset", "Largest apartment available", "In-unit laundry and parking", "Private yard and storage"],
    },
    {
      id: 19,
      craigslist_id: "7789234519",
      title: "Artistic Studio in Mission - Creative Space",
      price: 2100,
      location: "mission district",
      bedrooms: 0,
      sqft: 500,
      price_per_sqft: 4.2,
      value_score: 9.3,
      reasons: ["21% below neighborhood average", "Vibrant, walkable neighborhood", "Pet-friendly", "Unique artistic character"],
    },
    {
      id: 9,
      craigslist_id: "7789234509",
      title: "Large 2BR in Sunset District - Quiet Neighborhood",
      price: 2600,
      location: "sunset / parkside",
      bedrooms: 2,
      sqft: 900,
      price_per_sqft: 2.89,
      value_score: 9.1,
      reasons: ["Excellent price per sqft", "In-unit laundry", "Garage parking included", "Private backyard"],
    },
    {
      id: 25,
      craigslist_id: "7789234525",
      title: "Affordable 2BR in Bayview - Great Deal",
      price: 2400,
      location: "bayview",
      bedrooms: 2,
      sqft: 800,
      price_per_sqft: 3.0,
      value_score: 8.9,
      reasons: ["Great value for 2BR", "Spacious rooms", "Pet-friendly", "Near public transit"],
    },
    {
      id: 12,
      craigslist_id: "7789234512",
      title: "Simple 1BR in Mission - Good Value",
      price: 2300,
      location: "mission district",
      bedrooms: 1,
      sqft: 600,
      price_per_sqft: 3.83,
      value_score: 8.7,
      reasons: ["13% below neighborhood average", "Near BART station", "Pet-friendly", "Great restaurants nearby"],
    },
  ],
  amenities_breakdown: {
    cats_allowed: 19,
    dogs_allowed: 14,
    in_unit_laundry: 10,
    in_building_laundry: 5,
    shared_laundry: 7,
    coin_laundry: 3,
    parking_included: 8,
    parking_garage: 9,
    parking_street: 11,
    parking_none: 2,
  },
  bedroom_stats: {
    studio: {
      count: 9,
      avg_price: 2455,
      avg_sqft: 483,
      avg_price_per_sqft: 5.18,
    },
    "1br": {
      count: 12,
      avg_price: 2754,
      avg_sqft: 667,
      avg_price_per_sqft: 4.21,
    },
    "2br": {
      count: 7,
      avg_price: 3214,
      avg_sqft: 950,
      avg_price_per_sqft: 3.46,
    },
    "3br": {
      count: 2,
      avg_price: 3600,
      avg_sqft: 1300,
      avg_price_per_sqft: 2.82,
    },
  },
};
